services:
  app:
    build: .
    container_name: cronogramamb
    environment:
      DATABASE_URL: postgresql://mbuser:tUIPIITg0AeY0cxw2Sk1@dbpostgre:5432/cronograma
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cronogramamb.rule=Host(`mbnexusti.mbsp.mx`)"
      - "traefik.http.routers.cronogramamb.entrypoints=websecure"
      - "traefik.http.routers.cronogramamb.tls=true"
      - "traefik.http.routers.cronogramamb.tls.certresolver=letsencrypt"
      - "traefik.http.services.cronogramamb.loadbalancer.server.port=3000"
    networks:
      - default
      - traefik-net
    restart: unless-stopped

networks:
  traefik-net:
    external: true
